# Generated by Django 5.2.4 on 2025-07-09 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_items_sold', models.IntegerField(default=0)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('unique_customers', models.IntegerField(default=0)),
                ('morning_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('afternoon_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('evening_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('night_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sales Analytics',
                'verbose_name_plural': 'Sales Analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('page_views', models.IntegerField(default=0)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('sessions', models.IntegerField(default=0)),
                ('bounce_rate', models.FloatField(default=0.0)),
                ('avg_session_duration', models.FloatField(default=0.0)),
                ('visitors_to_customers', models.IntegerField(default=0)),
                ('conversion_rate', models.FloatField(default=0.0)),
                ('organic_traffic', models.IntegerField(default=0)),
                ('direct_traffic', models.IntegerField(default=0)),
                ('social_traffic', models.IntegerField(default=0)),
                ('referral_traffic', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Website Analytics',
                'verbose_name_plural': 'Website Analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('new_customers', models.IntegerField(default=0)),
                ('returning_customers', models.IntegerField(default=0)),
                ('total_active_customers', models.IntegerField(default=0)),
                ('avg_customer_lifetime_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_order_frequency', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='ProductAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=200)),
                ('product_category', models.CharField(blank=True, max_length=100)),
                ('units_sold', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('views', models.IntegerField(default=0)),
                ('conversion_rate', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-date', '-units_sold'],
                'unique_together': {('date', 'product_id')},
            },
        ),
    ]
