# Generated by Django 4.2.11 on 2025-07-09 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerAnalytics',
        ),
        migrations.DeleteModel(
            name='ProductAnalytics',
        ),
        migrations.DeleteModel(
            name='SalesAnalytics',
        ),
        migrations.DeleteModel(
            name='WebsiteAnalytics',
        ),
    ]
