# Generated by Django 4.2.11 on 2025-07-09 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminaction',
            name='admin_user',
        ),
        migrations.DeleteModel(
            name='AdminNotification',
        ),
        migrations.DeleteModel(
            name='DashboardMetrics',
        ),
        migrations.DeleteModel(
            name='AdminAction',
        ),
    ]
