# Generated by Django 4.2.11 on 2025-07-17 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_cardinfo_fiscalcondition_ivacondition_orderdetail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='iva_condition',
        ),
        migrations.DeleteModel(
            name='IvaCondition',
        ),
    ]
