# Generated by Django 5.2.4 on 2025-07-09 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_audit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='affected_table',
            field=models.CharField(choices=[('Product', 'Product'), ('Category', 'Category'), ('Brand', 'Brand')], max_length=100),
        ),
    ]
