# Generated by Django 4.2.11 on 2025-07-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_audit_affected_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='affected_table',
            field=models.CharField(choices=[('Name', 'Name'), ('Category', 'Category'), ('Brand', 'Brand'), ('Description', 'Description'), ('Stock', 'Stock')], max_length=100),
        ),
    ]
